services:
  _defaults:
    autowire: true
    autoconfigure: true

  PhpGuild\UserBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources,PhpGuildUserBundle.php}'

  PhpGuild\UserBundle\EventSubscriber\UserSubscriber:
    tags:
      - { name: 'doctrine.event_subscriber' }

  PhpGuild\UserBundle\EventSubscriber\DoctrineClassMetadata\:
    resource: ../../EventSubscriber/DoctrineClassMetadata
    tags:
      - { name: doctrine.event_subscriber, priority: 256 }
